### ISSUE TITLE
where is the cfg.json? 

### ISSUE THREAD

**Issue by Tomingz** [skyoung/RFL#1]
I have already downloaded basketball sequence from OTB-100,and put it in C:/Users/acer/Desktop/程序/RFL-master/output/models
when I run tracking.demo.py,there is a bug:

 File "C:/Users/acer/Desktop/程序/RFL-master/tracking/tracking_demo.py", line 57, in load_seq_config
    configFile = open(src)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/acer/Desktop/程序/RFL-master\\Basketball\\cfg.json'

**Comment by tyyyang** [comment]
Fixed it in the new update. Please check.

**Comment by Tomingz** [comment]
@skyoung  ok, thank u ,it works
